### ISSUE TITLE
References to Private/Nonexistent Gitlab Repos

### ISSUE THREAD

**Issue by ginglis13** [lyokum/cscli#1]
See line 7 of `parser.go`:

```go
package main
import (
	"bytes"
	"errors"
	"fmt"
	"gitlab.com/lyokum/attr"
	"golang.org/x/net/html"
	"log"
	"os/exec"
	"strconv"
	"strings"
	"sync"
)
```

**Comment by lyokum** [comment]
Did you follow the installation instructions, specifically `go get golang.org/x/net/html`?

**Comment by ginglis13** [comment]
Yes i did. I will run thru them again to double check

**Comment by ginglis13** [comment]
`lyokum/cscli/parser.go:7:2: cannot find package "gitlab.com/lyokum/attr" in any of:
        /usr/lib/go/src/gitlab.com/lyokum/attr (from $GOROOT)
        /home/ginglis/go/src/gitlab.com/lyokum/attr (from $GOPATH)
lyokum/cscli/class.go:6:2: cannot find package "gitlab.com/lyokum/update" in any of:
        /usr/lib/go/src/gitlab.com/lyokum/update (from $GOROOT)
        /home/ginglis/go/src/gitlab.com/lyokum/update (from $GOPATH)
`

**Comment by lyokum** [comment]
Ah, I made a mistake on my end. Let me fix it and push an update. I put my files under a gitlab folder rather than a github folder locally

**Comment by lyokum** [comment]
Okay, I think I fixed the gitlab references. Run `go get github.com/lyokum/cscli` and `go get github.com/lyokum/notify-server`, and then run `go install github.com/lyokum/cscli` again

**Comment by ginglis13** [comment]
working now, thanks!

**Comment by lyokum** [comment]
Awesome, glad to hear it! I'll mark this as closed
